// CEG — News & Insights content
// Each article: slug, title, date, category, author, excerpt, body[], image, tags, readTime

const CEG_NEWS = [
  {
    slug: "navfac-macc-award-2025",
    title: "Coastal Engineering Group Awarded NAVFAC Mid-Atlantic MACC Task Order",
    date: "April 14, 2025",
    dateISO: "2025-04-14",
    category: "Press Release",
    author: "CEG Communications",
    readTime: "3 min read",
    excerpt: "Coastal Engineering Group has been awarded a NAVFAC Mid-Atlantic Multiple Award Construction Contract task order for waterfront rehabilitation at a Mid-Atlantic naval installation. Work begins Q3 2025.",
    image: "/assets/diver-city.jpg",
    tags: ["NAVFAC", "Federal", "Contract Award"],
    body: [
      "Coastal Engineering Group (CEG) has been awarded a task order under the NAVFAC Mid-Atlantic Multiple Award Construction Contract (MACC) for waterfront rehabilitation services at a Mid-Atlantic naval installation. The award represents a continued expansion of CEG's federal waterfront portfolio across the region.",
      "The scope of work includes underwater inspection, pile jacket repairs, and concrete rehabilitation across multiple pier structures, with construction scheduled to begin in Q3 2025. CEG will self-perform all diving, construction, and QA/QC operations under the contract.",
      "\"This award reflects the trust NAVFAC places in our team's ability to deliver complex waterfront work in an active operational environment,\" said the CEG Executive Team. \"Our PE-led dive teams and EM385-compliant safety program were key differentiators in this selection.\"",
      "As a Veteran-Owned Small Business (VOSB) pre-qualified under NAVFAC's MACC program, CEG is positioned to compete on task orders across the Mid-Atlantic and Southeast regions. The company currently holds pre-qualifications with multiple NAVFAC and USACE districts.",
    ],
  },
  {
    slug: "jacksonville-office-expansion",
    title: "CEG Opens Jacksonville Operations Hub to Support Southeast Growth",
    date: "March 3, 2025",
    dateISO: "2025-03-03",
    category: "News",
    author: "CEG Communications",
    readTime: "2 min read",
    excerpt: "Coastal Engineering Group has established a permanent operations base in Jacksonville, Florida, positioning the company to better serve NAVFAC Southeast, port authorities, and commercial clients across the Gulf Coast and Southeast Atlantic.",
    image: "/assets/marine-construction.jpg",
    tags: ["Growth", "Southeast", "Operations"],
    body: [
      "Coastal Engineering Group has established a permanent operations hub in Jacksonville, Florida — the company's second regional base after its Greenwood Lake, NY headquarters. The expansion positions CEG to better support federal and commercial clients across the Southeast Atlantic and Gulf Coast markets.",
      "Jacksonville provides direct access to Naval Station Mayport, NAVFAC Southeast contracting offices, the Port of Jacksonville, and a growing pipeline of coastal infrastructure projects across Florida, Georgia, and the Carolinas.",
      "The hub will support a dedicated dive team, project management staff, and equipment staging for Southeast operations. The company has already completed two federal projects out of the Jacksonville base, with additional task orders currently in negotiation.",
      "\"The Southeast is one of the most active markets for waterfront infrastructure investment in the country,\" noted CEG leadership. \"Having a permanent team and equipment on the ground means faster response times and more competitive pricing for our clients in the region.\"",
    ],
  },
  {
    slug: "pe-led-diving-roi",
    title: "Why PE-Led Diving Changes the ROI on Underwater Infrastructure Inspection",
    date: "February 18, 2025",
    dateISO: "2025-02-18",
    category: "Industry Insight",
    author: "CEG Engineering",
    readTime: "5 min read",
    excerpt: "When a Professional Engineer leads the dive rather than reviewing footage afterward, inspection cycles get shorter, repair decisions get faster, and mobilization costs drop. Here's how the math works.",
    image: "/assets/commercial-diving.jpg",
    tags: ["PE Diving", "Inspection", "Engineering"],
    body: [
      "The standard model for underwater infrastructure inspection looks like this: a commercial dive team documents conditions, surfaces with footage and photographs, and an engineer reviews the data — sometimes days or weeks later — before issuing a condition report. It's a two-step process built on a handoff.",
      "CEG operates differently. Our lead divers hold Professional Engineer licenses, which means structural assessment happens in real time, underwater. When a PE diver identifies a defect, they evaluate it with engineering judgment on the spot — not retrospectively from video.",
      "The practical impact is significant. A traditional inspection cycle that spans three to six weeks from mobilization to stamped report can be compressed to seven to ten days when the PE is in the water. Repair recommendations are drafted with engineering authority from the first debrief. Owners get actionable data faster.",
      "There's also a cost dimension. Every additional mobilization to revisit a structure — because the initial report raised questions that required another look — adds cost and schedule. PE-led inspections reduce re-dive rates because the engineering judgment that typically generates follow-up questions is applied during the initial dive.",
      "For federal clients operating under NAVFAC or USACE oversight, PE-stamped deliverables remove an additional review layer that often adds weeks to approval timelines. The report lands pre-qualified.",
      "This model isn't appropriate for every inspection — routine Level 1 surveys in straightforward conditions don't necessarily require it. But for structures with known deterioration, complex substructure geometry, or active operational constraints, deploying a PE diver at the front of the project consistently produces better outcomes than the traditional two-step.",
    ],
  },
  {
    slug: "greenwood-lake-dam-complete",
    title: "Greenwood Lake Dam Rehabilitation Design Delivered, Construction Procurement Underway",
    date: "December 9, 2024",
    dateISO: "2024-12-09",
    category: "Project Update",
    author: "CEG Communications",
    readTime: "2 min read",
    excerpt: "CEG has completed the spillway redesign and embankment stabilization design package for the Greenwood Lake Dam, with NYSDEC permits in hand and the Greenwood Lake Commission moving toward construction procurement.",
    image: "/assets/federal-project-dam.jpg",
    tags: ["Dam Safety", "ASDSO", "State & Local"],
    body: [
      "Coastal Engineering Group has completed the engineering design package for the Greenwood Lake Dam Rehabilitation project on behalf of the Greenwood Lake Commission in New York. The full PE-stamped design — including spillway redesign, embankment stabilization, and construction documents — has been permitted through the New York State Department of Environmental Conservation (NYSDEC).",
      "The project began with a full ASDSO-certified dam safety inspection that identified spillway deterioration and embankment stability concerns requiring engineering intervention. CEG's inspection findings drove the design scope directly, eliminating the gap between assessment and solution that typically adds time and cost to dam rehabilitation projects.",
      "\"Greenwood Lake is a recreational resource that a lot of people depend on,\" said the project engineer. \"Getting the permitting right and moving into construction on a defined schedule was the priority, and the integrated inspection-to-design approach let us do that efficiently.\"",
      "The Greenwood Lake Commission is currently advancing toward construction contractor procurement using the CEG-prepared construction document package. CEG is available for construction phase engineering support and QA/QC oversight as the project advances.",
    ],
  },
  {
    slug: "atlantic-shores-mobilization",
    title: "CEG Marine Services Supports Atlantic Shores Offshore Wind Cable Lay Operations",
    date: "November 5, 2024",
    dateISO: "2024-11-05",
    category: "Project Update",
    author: "CEG Communications",
    readTime: "2 min read",
    excerpt: "CEG's marine services division is providing tug and deck barge support for Atlantic Shores Offshore Wind cable lay vessel operations off the New Jersey coast, supporting one of the region's largest offshore wind development projects.",
    image: "/assets/marine-services.jpg",
    tags: ["Energy", "Offshore Wind", "Marine Services"],
    body: [
      "Coastal Engineering Group's marine services division has mobilized tug and deck barge assets in support of Atlantic Shores Offshore Wind's cable lay vessel operations off the New Jersey coast. The engagement supports one of the largest offshore wind development projects currently underway on the US East Coast.",
      "CEG is providing dedicated vessel positioning, port-to-site tug escort, and logistics coordination integrated directly with the cable lay vessel's operational schedule. The work requires precise timing around weather windows and coordinated port transits through the Port of New Jersey.",
      "The Atlantic Shores project represents CEG's continued expansion into offshore energy support — a market segment where the company's combination of marine operations experience, owned vessel assets, and 24/7 response capability provides a meaningful advantage over logistics-only contractors.",
      "Marine services support is ongoing through the cable lay campaign, with additional scope options under active discussion for the project's next phases.",
    ],
  },
  {
    slug: "csx-bridge-inspection-complete",
    title: "Railroad Bridge Inspection for CSX Delivered with Zero Rail Service Disruption",
    date: "September 22, 2024",
    dateISO: "2024-09-22",
    category: "Project Update",
    author: "CEG Communications",
    readTime: "2 min read",
    excerpt: "CEG completed a full structural underwater inspection of a CSX overwater railroad bridge in New York, delivering a PE-stamped condition report in 10 business days with no interruption to daily freight operations.",
    image: "/assets/railroad-bridge-inspection.jpg",
    tags: ["Bridge Inspection", "Commercial", "Diving"],
    body: [
      "Coastal Engineering Group has completed an underwater structural inspection of a CSX Transportation overwater railroad bridge in New York, delivering a PE-stamped condition report within 10 business days of mobilization — with zero disruption to active rail freight operations across the crossing.",
      "The inspection required evaluating 47 submerged timber pile elements across three span crossings while coordinating around CSX's daily freight schedule. CEG's two-person ADCI dive team, led by a PE diver, conducted real-time structural evaluation at depth — identifying priority repair items and material conditions without requiring a post-dive engineering review cycle.",
      "\"Active railroad bridges present unique access and scheduling constraints,\" noted the project manager. \"The ability to complete the engineering assessment in-water rather than in a follow-up office review is what let us turn the report around in 10 days.\"",
      "CEG has provided the report to CSX with prioritized repair recommendations and engineered repair options for their maintenance planning cycle. The company is available to provide repair design and construction services as the client advances the project.",
    ],
  },
];

window.CEG_NEWS = CEG_NEWS;
